"""create discussion_messages table

Revision ID: 6652e4aaa856
Revises: d7a5b971e731
Create Date: 2026-08-08 21:31:10.257384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6652e4aaa856'
down_revision: Union[str, Sequence[str], None] = 'd7a5b971e731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_messages',
    sa.Column('discussion_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("message_type IN ('host_intro', 'host_summary', 'agent_think', 'agent_speak', 'user_intervene')", name='ck_dm_message_type'),
    sa.ForeignKeyConstraint(['agent_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dm_discussion_round_created', 'discussion_messages', ['discussion_id', 'round_number', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dm_discussion_round_created', table_name='discussion_messages')
    op.drop_table('discussion_messages')
    # ### end Alembic commands ###