"""add audit_events table

Revision ID: ab1a621f72a1
Revises: 6652e4aaa856
Create Date: 2026-08-16 15:15:42.256856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ab1a621f72a1'
down_revision: Union[str, Sequence[str], None] = '6652e4aaa856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('discussion_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=4), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("level IN ('P0', 'P1', 'P2')", name='ck_audit_events_level'),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ae_discussion_created', 'audit_events', ['discussion_id', 'created_at'], unique=False)
    op.create_index('idx_ae_event_type_created', 'audit_events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_ae_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ae_user_created', table_name='audit_events')
    op.drop_index('idx_ae_event_type_created', table_name='audit_events')
    op.drop_index('idx_ae_discussion_created', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###