"""create skills table

Revision ID: c4106078694b
Revises: 42d257421768
Create Date: 2026-08-08 13:47:05.768649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c4106078694b'
down_revision: Union[str, Sequence[str], None] = '42d257421768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('generating', 'ready', 'error')", name='ck_skills_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skills_owner_created', 'skills', ['owner_id', 'created_at'], unique=False)
    op.create_index('idx_skills_owner_name_unique', 'skills', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_skills_public_created', 'skills', ['is_public', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_skills_public_created', table_name='skills', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_skills_owner_name_unique', table_name='skills', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_skills_owner_created', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###